language: csharp
solution: MBINCompiler.sln
mono: latest
dotnet: 2.2.109
before_install:
    # Set the `python` command to be python 3
    - pyenv install 3.6.3
    - pyenv global 3.6.3
install:
    - export FrameworkPathOverride=$(dirname $(which mono))/../lib/mono/4.6.1/
    - python3.6 -m pip install --user pytest requests
script:
    - dotnet restore
    - dotnet build -r win-x64 -p:Configuration=Release /nowarn:cs0618
    # Build a linux version for running python tests
    - dotnet restore
    - dotnet build -r ubuntu.16.04-x64 -p:Configuration=Release /nowarn:cs0618
    # cwd: /home/travis/build/monkeyman192/MBINCompiler
    - sudo chmod +x Build/Release/ubuntu.16.04-x64/MBINCompiler.exe
    # Run the tests
    - python3.6 -m pytest --platform ubuntu.16.04-x64 --tb=no

    #- msbuild /p:Configuration=Release MBINCompiler.sln
    #- dotnet test

before_deploy:
    - export LIBMBIN_VERSION="$(cat libMBIN/Source/Version.cs | grep -P 'const[[:space:]]+string[[:space:]]+VERSION_STRING' | grep -oP '[0-9]+[.][0-9]+[.][0-9]+[.][0-9]+')"
    - "echo \"LIBMBIN_VERSION: $LIBMBIN_VERSION\""
    - "[[ \"$TRAVIS_TAG\" =~ ^v([[:digit:]]+)[.]([[:digit:]]+)[.]([[:digit:]]+)(-[^[:digit:]]+([[:digit:]]+)|[.]([[:digit:]])+) ]] && export MATCH_TAG=${BASH_REMATCH[1]}.${BASH_REMATCH[2]}.${BASH_REMATCH[3]}.${BASH_REMATCH[5]}${BASH_REMATCH[6]}"
    - "echo \"Tag: $TRAVIS_TAG -> $MATCH_TAG\""
    - "[[ \"$MATCH_TAG\" == \"$LIBMBIN_VERSION\" ]] && echo \"$TRAVIS_TAG matches LIBMBIN_VERSION.\" || echo \"Error: The version tag $TRAVIS_TAG must match the LIBMBIN_VERSION defined in Version.cs\" && set -e"
    #
    # Set up git user name and tag this commit
    #
    #- export TRAVIS_TAG=v$LIBMBIN_VERSION-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)
    #- git config --local user.name "Travis-CI"
    #- git config --local user.email "noreply@email.com"
    #- git tag $TRAVIS_TAG

# see https://docs.travis-ci.com/user/deployment/releases/
deploy:
    provider: releases
    prerelease: true
    name: "${TRAVIS_TAG}"
    body: "${TRAVIS_TAG}"
    api_key: "${GITHUB_TOKEN}"
    skip_cleanup: true
    file:
        - "Build/Release/libMBIN.dll"
        - "Build/Release/win-x64/MBINCompiler.exe"
    on:
        branch: development
        tags: true
        condition: "$TRAVIS_TAG =~ ^v[[:digit:]]"

deploy:
    provider: releases
    name: "${TRAVIS_TAG}"
    body: "${TRAVIS_TAG}"
    api_key: "${GITHUB_TOKEN}"
    skip_cleanup: true
    file:
        - "Build/Release/libMBIN.dll"
        - "Build/Release/win-x64/MBINCompiler.exe"
    on:
        branch: master
        tags: true
        condition: "$TRAVIS_TAG =~ ^v[[:digit:]]"
