version: 2
jobs:
    build-docs:
        docker:
            - image: python:3.7
        steps:
            - checkout
            - run:
                name: Install dependencies
                command: pip install mkdocs
            - run:
                name: Build docs
                command: mkdocs build
            - persist_to_workspace:
                root: html_docs
                paths: site
            - store_artifacts:
                path: html_docs/site
                destination: html
    deploy-docs:
        docker:
            - image: node:8.10.0
        steps:
            - checkout
            - attach_workspace:
                at: html_docs
            - run:
                name: Disable jekyll builds
                command: touch html_docs/site/.nojekyll
            - run:
                name: Install and configure dependencies
                command: |
                  npm install -g --silent gh-pages@2.0.1
                  git config user.email "mq-meg-circle@mq.edu.au"
                  git config user.name "circle CI"
            - add_ssh_keys:
                fingerprints:
                    - "2c:80:17:37:05:b1:db:88:0c:01:91:76:04:fe:b3:4c"
            - run:
                name: Deploy docs to gh-pages branch
                command: gh-pages --dotfiles --message "[skip ci] Auto-update" --dist html_docs/site

workflows:
    version: 2
    build:
        jobs:
            - build-docs
            - deploy-docs:
                requires:
                    - build-docs
                filters:
                    branches:
                        only: development